spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/settlement_shop
    username: settlement
    password: settlement
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  batch:
    jdbc:
      initialize-schema: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug