spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/settlement_shop
    username: settlement
    password: settlement

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: none

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false   # 부팅할 때 Job 자동 실행 막기