CREATE TABLE IF NOT EXISTS tb_brand (
    brand_id    BIGSERIAL    PRIMARY KEY,
    brand_code  VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(200) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',

    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by  VARCHAR(100) NOT NULL DEFAULT 'system',
    updated_by  VARCHAR(100) NOT NULL DEFAULT 'system'
);

CREATE TABLE IF NOT EXISTS tb_product (
    product_id  BIGSERIAL    PRIMARY KEY,
    brand_id    BIGINT       NOT NULL,
    item_code   VARCHAR(50)  NOT NULL UNIQUE,
    item_name   VARCHAR(200) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',

    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by  VARCHAR(100) NOT NULL DEFAULT 'system',
    updated_by  VARCHAR(100) NOT NULL DEFAULT 'system'
);
CREATE INDEX IF NOT EXISTS idx_product_brand_id ON tb_product(brand_id);

-- 2) Order / Delivery
CREATE TABLE IF NOT EXISTS tb_order (
    order_id           BIGSERIAL    PRIMARY KEY,
    order_no           VARCHAR(50)  NOT NULL UNIQUE,
    brand_id           BIGINT       NOT NULL,
    product_id         BIGINT       NOT NULL,
    item_code          VARCHAR(50)  NOT NULL,
    item_name          VARCHAR(200) NOT NULL,
    qty                INTEGER       NOT NULL CHECK (qty > 0),
    unit_price         NUMERIC(15,2) NOT NULL CHECK (unit_price >= 0),
    amount             NUMERIC(15,2) NOT NULL CHECK (amount >= 0),
    status             VARCHAR(20)   NOT NULL,   -- CHECK 제거 (Application enum으로 관리)
    ordered_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    status_changed_at  TIMESTAMPTZ   NULL,
    settled_at         TIMESTAMPTZ   NULL,

    created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by         VARCHAR(100)  NOT NULL DEFAULT 'system',
    updated_by         VARCHAR(100)  NOT NULL DEFAULT 'system'
);
-- 집계 대상 빠른 추출(부분 인덱스)
CREATE INDEX IF NOT EXISTS idx_order_unsettled_completed
    ON tb_order(status, settled_at)
    WHERE status = 'COMPLETED' AND settled_at IS NULL;
-- 조회(브랜드/상태/주문일)
CREATE INDEX IF NOT EXISTS idx_order_brand_status_ordered
    ON tb_order(brand_id, status, ordered_at);

CREATE TABLE tb_delivery (
         delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         order_id BIGINT NOT NULL,
         delivery_dt TIMESTAMP NOT NULL,
         delivery_fee NUMERIC(12, 2) NOT NULL DEFAULT 0,
         created_by VARCHAR(100),
         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         updated_by VARCHAR(100),
         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
         CONSTRAINT fk_tb_delivery_order
             FOREIGN KEY (order_id)
                 REFERENCES tb_order (order_id),
         CONSTRAINT ck_tb_delivery_fee_non_negative
             CHECK (delivery_fee >= 0)
);
CREATE UNIQUE INDEX uq_tb_delivery_order_id ON tb_delivery (order_id);
CREATE INDEX idx_tb_delivery_delivery_dt ON tb_delivery (delivery_dt);


-- 3) Sales (원장/집계)
CREATE TABLE IF NOT EXISTS tb_sales_detail (
    sales_detail_id BIGSERIAL    PRIMARY KEY,
    order_no        VARCHAR(50)  NOT NULL UNIQUE,
    sales_date      DATE         NOT NULL, -- date(delivery_dt)
    brand_id        BIGINT       NOT NULL,
    item_code       VARCHAR(50)  NOT NULL,
    item_name       VARCHAR(200) NOT NULL,
    qty             INTEGER       NOT NULL,
    amount          NUMERIC(15,2) NOT NULL,
    delivery_fee    NUMERIC(15,2) NOT NULL,
    status          VARCHAR(20)   NOT NULL, -- CHECK 제거

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(100) NOT NULL DEFAULT 'system',
    updated_by      VARCHAR(100) NOT NULL DEFAULT 'system'
);
CREATE INDEX IF NOT EXISTS idx_sales_detail_date_brand_item
    ON tb_sales_detail(sales_date, brand_id, item_code);

-- Daily
CREATE TABLE IF NOT EXISTS tb_sales_daily (
    sales_daily_id    BIGSERIAL    PRIMARY KEY,
    sales_day         DATE         NOT NULL,
    brand_id          BIGINT       NOT NULL,
    item_code         VARCHAR(50)  NOT NULL,
    item_name         VARCHAR(200) NOT NULL,
    order_cnt         INTEGER       NOT NULL,
    qty_sum           INTEGER       NOT NULL,
    amount_sum        NUMERIC(15,2) NOT NULL,
    delivery_fee_sum  NUMERIC(15,2) NOT NULL,

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by        VARCHAR(100) NOT NULL DEFAULT 'system',
    updated_by        VARCHAR(100) NOT NULL DEFAULT 'system',

    CONSTRAINT uq_sales_daily UNIQUE (sales_day, brand_id, item_code)
);

-- Monthly
CREATE TABLE IF NOT EXISTS tb_sales_monthly (
    sales_monthly_id  BIGSERIAL    PRIMARY KEY,
    sales_month       VARCHAR(7)   NOT NULL, -- YYYY-MM (형식 CHECK 제거)
    brand_id          BIGINT       NOT NULL,
    item_code         VARCHAR(50)  NOT NULL,
    item_name         VARCHAR(200) NOT NULL,
    order_cnt         INTEGER       NOT NULL,
    qty_sum           INTEGER       NOT NULL,
    amount_sum        NUMERIC(15,2) NOT NULL,
    delivery_fee_sum  NUMERIC(15,2) NOT NULL,

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by        VARCHAR(100) NOT NULL DEFAULT 'system',
    updated_by        VARCHAR(100) NOT NULL DEFAULT 'system',

    CONSTRAINT uq_sales_monthly UNIQUE (sales_month, brand_id, item_code)
);

-- Yearly
CREATE TABLE IF NOT EXISTS tb_sales_yearly (
    sales_yearly_id   BIGSERIAL    PRIMARY KEY,
    sales_year        VARCHAR(4)   NOT NULL, -- YYYY (형식 CHECK 제거)
    brand_id          BIGINT       NOT NULL,
    item_code         VARCHAR(50)  NOT NULL,
    item_name         VARCHAR(200) NOT NULL,
    order_cnt         INTEGER       NOT NULL,
    qty_sum           INTEGER       NOT NULL,
    amount_sum        NUMERIC(15,2) NOT NULL,
    delivery_fee_sum  NUMERIC(15,2) NOT NULL,

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by        VARCHAR(100) NOT NULL DEFAULT 'system',
    updated_by        VARCHAR(100) NOT NULL DEFAULT 'system',

    CONSTRAINT uq_sales_yearly UNIQUE (sales_year, brand_id, item_code)
);